/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mutualchia.vistas;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mutualchia.Conexion;
import mutualchia.entidades.Afiliado;
import mutualchia.modelo.AfiliadoData;

/**
 *
 * @author Cacho
 */
public class AfiliadoVista extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private AfiliadoData ad;
    private List<Afiliado> listaAfiliados;
    private Afiliado afi;
    
    /**
     * Creates new form AfiliadoVista
     */
    public AfiliadoVista() {
        try {
            initComponents();
            modelo= new DefaultTableModel ();
            armarCabecera();
            ad = new AfiliadoData (new Conexion());
            cargarDatos(-1);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error de Conexion");
      
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDnii = new javax.swing.JTextField();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAfiliados = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbActivo = new javax.swing.JCheckBox();
        btLimpiar = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        btModificar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("LISTADO DE AFILIADOS");

        jLabel2.setText("Ingrese un DNI");

        btNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.setEnabled(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        tbAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Activo"
            }
        ));
        tbAfiliados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAfiliadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAfiliados);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Datos del Afiliado");

        jLabel4.setText("idAfiliado");

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido");

        jLabel7.setText("Dni");

        jLabel8.setText("Activo");

        chbActivo.setEnabled(false);

        btLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpiar.setText("Limpiar");

        tfId.setEditable(false);

        tfNombre.setEditable(false);

        tfApellido.setEditable(false);

        tfDni.setEditable(false);

        btModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btModificar.setText("Modificar");
        btModificar.setEnabled(false);
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(tfDnii, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscar)))
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(0, 84, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfDni, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbActivo)
                        .addGap(34, 34, 34)
                        .addComponent(btLimpiar)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalir)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDnii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btBuscar)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbActivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNuevo)
                    .addComponent(btGuardar)
                    .addComponent(btModificar)
                    .addComponent(btBorrar)
                    .addComponent(btSalir))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        if (afi==null){
            afi = new Afiliado();
            afi.setNombre(tfNombre.getText());
            afi.setApellido(tfApellido.getText());
            afi.setDni((Long.parseLong(tfDni.getText())));
            afi.setActivo(chbActivo.isSelected());
            System.out.println (afi.getNombre());
            System.out.println (afi.isActivo());
           
            ad.agregarAfiliado(afi);
            } else {
            afi.setIdAfiliado(Integer.parseInt(tfId.getText()));
                afi.setNombre(tfNombre.getText());
                afi.setApellido(tfApellido.getText());
                afi.setDni((Long.parseLong(tfDni.getText())));
                afi.setActivo(chbActivo.isSelected());
                ad.actualizarAfiliado(afi);
                
            }
             
            
  
        tfDnii.setText("");
        
        tfId.setEditable(false);
        tfNombre.setEditable(false);
        tfApellido.setEditable(false);
        chbActivo.setEnabled(false);
        btGuardar.setEnabled(false);
        cargarDatos (-1);
        afi=null;
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        tfDni.setEditable(true);
        tfNombre.setEditable(true);
        tfApellido.setEditable(true);
        chbActivo.setEnabled(true);
        btGuardar.setEnabled(true);
        btModificar.setEnabled(false);
    }//GEN-LAST:event_btModificarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try {
        long dniBuscar =Long.parseLong(tfDnii.getText());
        cargarDatos(dniBuscar);
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Usted debe introducir un numero");
        tfDnii.requestFocus();
        cargarDatos(-1);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tbAfiliadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAfiliadosMouseClicked
        // TODO add your handling code here:
        int fila = tbAfiliados.getSelectedRow();
        
        tfId.setText((int)tbAfiliados.getValueAt(fila, 0)+"");
        tfNombre.setText((String)tbAfiliados.getValueAt(fila, 1));
        tfApellido.setText((String)tbAfiliados.getValueAt(fila, 2));
        tfDni.setText((long)tbAfiliados.getValueAt(fila, 3)+"");
        chbActivo.setSelected((boolean)tbAfiliados.getValueAt(fila, 4));
        
        afi = new Afiliado ();
        afi.setIdAfiliado((int)tbAfiliados.getValueAt(fila, 0));
        afi.setNombre((String)tbAfiliados.getValueAt(fila, 1));
        afi.setApellido((String)tbAfiliados.getValueAt(fila, 2));
        afi.setDni((long)tbAfiliados.getValueAt(fila, 3));
        chbActivo.setSelected((boolean)tbAfiliados.getValueAt(fila, 4));
        btModificar.setEnabled(true);
        
    }//GEN-LAST:event_tbAfiliadosMouseClicked

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        // TODO add your handling code here: 
        limpiar();
        btGuardar.setEnabled(true);
        tfDni.setEditable(true);
        tfNombre.setEditable(true);
        tfApellido.setEditable(true);
        chbActivo.setEnabled(true);
        afi=null;
        
        
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
        int idAfiliadoABorrar= Integer.parseInt(tfId.getText());
        ad.borrarAfiliado(idAfiliadoABorrar);
        cargarDatos(-1);
        
    }//GEN-LAST:event_btBorrarActionPerformed

    public void limpiar() {
    tfId.setText("");
    tfNombre.setText("");
    tfApellido.setText("");
    tfDni.setText("");
    chbActivo.setSelected(false);
            }
    private void armarCabecera () {
            ArrayList<Object> titulos=new ArrayList<Object>();
            titulos.add("ID");
            titulos.add("Nombre");
            
            titulos.add("Apellido");
            titulos.add("Dni");
            titulos.add("Activo");
            for(Object it:titulos) {
                modelo.addColumn(it);
            }
            tbAfiliados.setModel(modelo);
            
        }
        
        private void cargarDatos (long dni) {
            borrarFilas ();
           listaAfiliados = ad.obtenerAfiliados();
           for(Afiliado a:listaAfiliados) {
               if(dni==-1){
            modelo.addRow(new Object[]{a.getIdAfiliado(),a.getNombre(),a.getApellido(),a.getDni(),a.isActivo()});
               }else{
                if(dni==a.getDni()) {
                modelo.addRow(new Object[]{a.getIdAfiliado(),a.getNombre(),a.getApellido(),a.getDni(),a.isActivo()});
                
                }
                       }
        
        }
        }
        
        private void borrarFilas (){
            int a =modelo.getRowCount()-1;
            for(int i=a;i>=0;i--){

                modelo.removeRow(i );
                

        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btSalir;
    private javax.swing.JCheckBox chbActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAfiliados;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDnii;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
