/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mutualchia.vistas;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mutualchia.Conexion;
import mutualchia.entidades.Orden;
import mutualchia.modelo.OrdenData;

/**
 *
 * @author Cacho
 */
public class AnularOrdenes extends javax.swing.JInternalFrame {
   private DefaultTableModel modelo;
    private Orden ord;
    private OrdenData od;
 private List<Orden> listaOrdenes;

    /**
     * Creates new form AnularOrdenes
     */
    public AnularOrdenes() {
        try {
        initComponents();
        modelo= new DefaultTableModel ();
        armarCabecera();
        od = new OrdenData (new Conexion());
       
          } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error de Conexion");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrdenes = new javax.swing.JTable();
        dcFecha = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ANULAR ORDENES");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Anular");

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de emision");

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tbOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOrdenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbOrdenes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(btSalir)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btBuscar))
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btSalir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try {
        Date fechaBuscar =Date.parseDate(dcFecha);
        Orden ord = od.buscarOrdenXFecha(fechaBuscar);
       
        if (ord!=null) {
        dcFecha.setMaxSelectableDate(fechaBuscar);
        
        } else {
        JOptionPane.showMessageDialog(this, "Fecha no encontrada");
        dcFecha.requestFocus();
        }
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, "No hay ordenes emitidas");
        dcFecha.requestFocus();
        
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tbOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOrdenesMouseClicked
        // TODO add your handling code here:
int fila = tbOrdenes.getSelectedRow();
    ord = new Orden();
            
            //Prestador p = new Prestador();
            ord.getFecha();
            //hor.setPrestador(p);
            
            int fila=tbOrdenes.getSelectedRow();
            Integer idHorario = (Integer) tbOrdenes.getValueAt(fila, 0);
        Date fechaTurno = (Date) tbOrdenes.getValueAt(fila, 1);
        String Prestador = (String) tbOrdenes.getValueAt(fila, 2);
        String Afiliafo = (String) tbOrdenes.getValueAt(fila, 3);
        
        ord.setIdOrden(idOrden);
        dcFecha.setEnabled(true);
 //Date.valueOf fecha = (String) tbOrden.getValueAt(fila, 1);
        
        //Boolean activo = (Boolean) tbOrden.getValueAt(fila, 2);
        //Integer idHorario = (Integer) tbOrden.getValueAt(fila, 0);
        //od.(idHorario);

    }//GEN-LAST:event_tbOrdenesMouseClicked
private void armarCabecera () {
            ArrayList<Object> titulos=new ArrayList<Object>();
            titulos.add("ID");
            titulos.add("FechaTurno");
            titulos.add("Prestador");
            titulos.add("Afiliado");
          
            for(Object it:titulos) {
                modelo.addColumn(it);
            }
            tbOrdenes.setModel(modelo);
}
private void cargarDatosHorarios () {
         try {
             borrarFilasOrdenes ();
             Orden orden =(Orden) dcFecha.getMaxSelectableDate();
             OrdenData od = new OrdenData(new Conexion());
             List <Orden> listaOrdenes=od.borrarOrden(orden.getIdOrden());
             for(Orden o:listaOrdenes) {
                 if(o.getFecha()) {
                 
                 
                 
                 modelo.addRow(new Object[]{o.getIdOrden(),o.getPrestador,o.getAfiliado(),o.getFechaTurno()});
                 }
                 
             }
         } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "Error al recuperar ordenes");
         }
}
 private void borrarFilasOrdenes (){
            int a =modelo.getRowCount()-1;
            for(int i=a;i>=0;i--){

                modelo.removeRow(i );
                

        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btSalir;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOrdenes;
    // End of variables declaration//GEN-END:variables
}
